"""
Query Planner: Analyzes Pydantic schemas to generate a QueryPlan.
Architecture: Schema -> Analyzer -> QueryPlan -> QuerySet
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel

from nova.query.relations import find_deep_relations

if TYPE_CHECKING:
    from nova.typing.models import NovaModel

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class QueryPlan:
    """
    Immutable data structure representing database query optimizations.
    Generated by the Query Planner based on a Pydantic schema.
    """
    select_related: list[str] = field(default_factory=list)
    prefetch_related: list[str] = field(default_factory=list)
    defer: list[str] = field(default_factory=list)
    only: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        """Check if the plan has no optimizations."""
        return not (self.select_related or self.prefetch_related or self.defer or self.only)


def analyze_schema_for_relations(
    schema: type[BaseModel, object],
    exclude: tuple[str, ...] = ()
) -> dict[str, list[str]]:
    """
    Entry point for schema analysis. Uses deep graph traversal.
    Filters out excluded fields.
    """
    visited: set[type[BaseModel]] = set()

    hints = find_deep_relations(schema=schema, visited=visited)

    if exclude:

        return {
            "select": [s for s in hints["select"] if s.split("__")[0] not in exclude],
            "prefetch": [p for p in hints["prefetch"] if p not in exclude]
        }

    return hints


def build_query_plan(model_class: type[NovaModel]) -> QueryPlan:
    """
    Main entry point to generate a QueryPlan for a specific model.
    """
    config = getattr(model_class, '_nova_config', None)

    if not config or not config.pydantic_schema:
        return QueryPlan()

    hints = analyze_schema_for_relations(
        schema=config.pydantic_schema,
        exclude=config.exclude_from_pydantic
    )

    return QueryPlan(
        select_related=hints["select"],
        prefetch_related=hints["prefetch"]
    )


def apply_plan(queryset: Any, plan: QueryPlan) -> Any:
    """Pure execution function. Applies a QueryPlan to a Django QuerySet."""
    qs = queryset

    if plan.select_related:
        qs = qs.select_related(*plan.select_related)
    if plan.prefetch_related:
        qs = qs.prefetch_related(*plan.prefetch_related)

    return qs


def apply_optimizations(queryset: Any, model_class: type[NovaModel]) -> Any:
    """Convenience wrapper for backward compatibility."""
    plan = build_query_plan(model_class)
    return apply_plan(queryset, plan)