#!/usr/bin/env python3
"""Generates an honest STATUS.md based on real code."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET

PROJECT_ROOT = Path(__file__).parent.parent
SRC_DIR = PROJECT_ROOT / "src" / "nova"
COVERAGE_XML = PROJECT_ROOT / "coverage.xml"
STATUS_MD = PROJECT_ROOT / "STATUS.md"


def parse_coverage() -> dict[str, float]:
    """Parses coverage.xml → {module_path: coverage_percent}."""
    if not COVERAGE_XML.exists():
        return {}

    tree = ET.parse(COVERAGE_XML)
    root = tree.getroot()

    coverage_map: dict[str, float] = {}

    for cls in root.iter("class"):
        filename = cls.get("filename", "")
        if not filename:
            continue

        filename = filename.replace("\\", "/")

        if filename.startswith("src/nova/"):
            module_path = filename.replace("src/nova/", "", 1).replace("/", ".").replace(".py", "")
        elif filename.startswith("nova/"):
            module_path = filename.replace("nova/", "", 1).replace("/", ".").replace(".py", "")
        else:
            module_path = filename.replace("/", ".").replace(".py", "")

        lines = cls.find("lines")
        if lines is None:
            continue

        total = len(lines.findall("line"))
        hits = sum(1 for line in lines.findall("line") if line.get("hits", "0") != "0")

        if total > 0:
            coverage_map[module_path] = round((hits / total * 100), 1)

    return coverage_map


def get_module_status(coverage: float) -> tuple[str, str]:
    """Returns (status, emoji) based on real metrics."""
    if coverage == 0.0:
        return "Not Implemented / No Tests", "🔴"
    if coverage < 50.0:
        return "Alpha — Unstable", "🟠"
    if coverage < 75.0:
        return "Beta — Use with Caution", "🟡"
    if coverage < 90.0:
        return "Stable — Needs More Tests", "🟢"
    return "Production Ready", "✅"


def scan_modules() -> list[dict[str, Any]]:
    """Scans src/nova and gathers metrics per module."""
    coverage_map = parse_coverage()
    modules: list[dict[str, Any]] = []

    for py_file in sorted(SRC_DIR.rglob("*.py")):
        if py_file.name.startswith("_"):
            continue

        rel_path = py_file.relative_to(SRC_DIR)
        module_name = str(rel_path.with_suffix("")).replace("/", ".")
        lines_count = len(py_file.read_text().splitlines())

        test_path = PROJECT_ROOT / "tests" / rel_path
        has_tests = test_path.exists() or any(
            (PROJECT_ROOT / "tests" / p / f"test_{py_file.name}").exists() for p in rel_path.parents
        )

        cov = coverage_map.get(module_name, 0.0)
        status, emoji = get_module_status(cov)

        modules.append(
            {
                "module": module_name,
                "lines": lines_count,
                "coverage": cov,
                "status": status,
                "emoji": emoji,
                "has_tests": has_tests,
            }
        )

    return modules


def generate_status_md(modules: list[dict[str, Any]]) -> str:
    """Generates deterministic markdown."""
    total_lines = sum(m["lines"] for m in modules)
    avg_coverage = (
        sum(m["coverage"] * m["lines"] for m in modules) / total_lines if total_lines else 0
    )
    ready_count = sum(1 for m in modules if m["coverage"] >= 75)

    md = f"""# 📊 Project Status — Auto-Generated

> **Generated from current repository state**
> **Generated by:** `scripts/generate_status.py`

## 🎯 Overall Health

| Metric | Value |
|---|---|
| **Total Modules** | {len(modules)} |
| **Avg Coverage (weighted)** | {avg_coverage:.1f}% |
| **Modules ≥75% coverage** | {ready_count}/{len(modules)} |
| **Modules with 0% tests** | {sum(1 for m in modules if m["coverage"] == 0)}/{len(modules)} |

## ⚠️ Honest Assessment

This project is **NOT "100% Enterprise Ready"**. Here's the real picture:

- **{sum(1 for m in modules if m["coverage"] == 0)} modules** have zero test coverage
- **{sum(1 for m in modules if m["coverage"] < 50 and m["coverage"] > 0)} modules** are below 50% (Alpha quality)
- **Ecosystem modules** (DRF, FastAPI, GraphQL) are largely untested proof-of-concepts
- **Async ORM** exists in code but has no tests — treat as experimental

## 📋 Module Breakdown

| Module | Lines | Coverage | Status |
|---|---|---|---|
"""

    for m in modules:
        cov_str = f"{m['coverage']:.1f}%" if m["coverage"] > 0 else "0%"
        md += f"| `{m['module']}` | {m['lines']} | {cov_str} | {m['emoji']} {m['status']} |\n"

    md += """
## 🚧 Known Limitations (Auto-Detected)

Based on coverage analysis:

"""
    zero_cov = [m for m in modules if m["coverage"] == 0]
    if zero_cov:
        md += "**Untested modules (do not use in production):**\n\n"
        for m in zero_cov:
            md += f"- `{m['module']}`\n"

    md += """
---

*This file is auto-generated. Do not edit manually. Run `python scripts/generate_status.py --write` to update.*
"""
    return md


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate honest STATUS.md")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Write STATUS.md to disk")
    group.add_argument("--check", action="store_true", help="Check if STATUS.md is up to date")
    args = parser.parse_args()

    if not COVERAGE_XML.exists():
        print(
            "ERROR: coverage.xml not found. Run 'uv run pytest --cov=src/nova --cov-report=xml' first.",
            file=sys.stderr,
        )
        return 1

    modules = scan_modules()
    content = generate_status_md(modules)

    if args.check:
        if not STATUS_MD.exists():
            print("ERROR: STATUS.md does not exist. Run with --write first.", file=sys.stderr)
            return 1
        existing = STATUS_MD.read_text(encoding="utf-8")
        if existing != content:
            print(
                "ERROR: STATUS.md is out of date. Run `python scripts/generate_status.py --write` to update.",
                file=sys.stderr,
            )
            return 1
        print("✅ STATUS.md is up to date.")
        return 0

    if args.write:
        STATUS_MD.write_text(content, encoding="utf-8")
        print(f"✅ Generated {STATUS_MD} with {len(modules)} modules")
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
